### ISSUE TITLE
Advance credits is a negative value in this contract

### ISSUE THREAD

**Issue by arpadgabor** [severedsolo/KerbalAcademy#10]
I accepted the contract to test if the advance is, indeed, a negative value. And it was. I am now 112k poorer..

I don't know if this was intended.

[image](https://user-images.githubusercontent.com/9270494/35983230-46d761b2-0cfa-11e8-8d7b-dbc3df8617b5.png)

**Comment by severedsolo** [comment]
As intended. You pay for the training in these contracts, they don't pay you.
