### ISSUE TITLE
GPP Compatibility

### ISSUE THREAD

**Issue by eberkain** [severedsolo/KerbalAcademy#6]
When loading the contract with [GPP](http://forum.kerbalspaceprogram.com/index.php?/topic/152136-122-galileos-planet-pack-official-release-v11/) I get some errors related to the stock planets not being there anymore.

**Comment by severedsolo** [comment]
Sadly Kerbal Academy is not/cannot be compatible with GPP as it relies on PQS Cities that only exist on Kerbin.
