### ISSUE TITLE
[issue] Engineer Training: Repair Contract

### ISSUE THREAD

**Issue by Delta-38** [severedsolo/KerbalAcademy#9]
Hi, I think there is a small bug with the Engineering School contract. 
Specifically it required me to bring a given Engineer to MinMus to fix a Lander's leg (in this case the lander was on it's way to an orbital station when I accepted the contract).
However after I distractedly docked the lander with the station to go back and fly said engineer there even if I undock and rename the intended target of the contract it doesn't trigger anymore.
So I'm stuck with this non working contract, what can I do expect decline it?
(I no longer have saves preceding the aformentioned docking operation)
Thanks in advance

**Comment by severedsolo** [comment]
Closed as Kerbal Academy is no longer supported

**Comment by Delta-38** [comment]
No problem, thanks anyway (BTW rereading this brought back fond memories anyway ) :)
